on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
  assets:
    name: Upload Assets
    runs-on: ubuntu-latest
    permissions:
      contents: write # release changes require contents write
    steps:
      - uses: actions/checkout@v3
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload <release_tag> <a_file>