name: Release Build
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Extract branch name
        id: branch
        shell: bash
        run: echo "name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
      - name: Build Firmware
        uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
      - name: Upload Release Artifacts
        run: |
          gh release create v1.2.3 release.tar.xz
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash